# Generated by Django 5.1 on 2024-08-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_color_car_gearshift_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='gearshift',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automático', 'Automático'), ('cvt', 'CVT')], max_length=10, null=True),
        ),
    ]
